#!/usr/bin/env python3
"""Generate the root-menu shim zips shipped in the recovery ramdisk.

TWRP only streams a script's output to its on-screen console when the script
runs as a flashable zip (via the OUTFD pipe, `ui_print <text>`). Each zip here
is a 1-file installer whose update-binary runs `twrp_root.sh <action>` and
forwards every output line to the console, returning the script's exit code
so failures show up red in TWRP.

Output: recovery/root/system/etc/twrp_root/<action>.zip
"""
import os
import stat
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "recovery", "root", "system", "etc", "twrp_root")

ACTIONS = ["status", "install-ksu", "install-magisk", "remove"]

UPDATE_BINARY = """#!/system/bin/bash
# TWRP root-menu shim for: twrp_root.sh {action}
# Generated by mkrootzips.py - do not edit by hand.
OUTFD="$2"
ui_print() {{ printf 'ui_print %s\\nui_print\\n' "$1" >&"$OUTFD"; }}
set -o pipefail
ui_print "== twrp_root: {action} (slot $(getprop ro.boot.slot_suffix))"
/system/bin/twrp_root.sh {action} 2>&1 | while IFS= read -r line; do ui_print "$line"; done
rc=$?
[ "$rc" -eq 0 ] || ui_print "!! twrp_root {action} failed (exit $rc)"
exit "$rc"
"""


def fixed_info(name, mode):
    info = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
    info.external_attr = (stat.S_IFREG | mode) << 16
    info.compress_type = zipfile.ZIP_DEFLATED
    return info


def main():
    os.makedirs(OUT, exist_ok=True)
    for action in ACTIONS:
        path = os.path.join(OUT, f"{action}.zip")
        with zipfile.ZipFile(path, "w") as z:
            z.writestr(fixed_info("META-INF/com/google/android/update-binary", 0o755),
                       UPDATE_BINARY.format(action=action))
            z.writestr(fixed_info("META-INF/com/google/android/updater-script", 0o644),
                       "# dummy - see update-binary\n")
        print(f"  wrote {os.path.relpath(path, HERE)}")


if __name__ == "__main__":
    main()
