#!/usr/bin/env python3
"""Generate the menu shim zips shipped in the recovery ramdisk.

TWRP only streams a script's output to its on-screen console when the script
runs as a flashable zip (via the OUTFD pipe, `ui_print <text>`). Each zip here
is a 1-file installer whose update-binary runs one command and forwards every
output line to the console, returning the command's exit code so failures
show up red in TWRP. The Advanced-menu entries queue and flash these zips.

Output: recovery/root/system/etc/twrp_root/<name>.zip
"""
import os
import stat
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "recovery", "root", "system", "etc", "twrp_root")

# zip name -> command it runs
ACTIONS = {
    # root menu (twrp_root.sh)
    "status": "/system/bin/twrp_root.sh status",
    "install-ksu": "/system/bin/twrp_root.sh install-ksu",
    "install-magisk": "/system/bin/twrp_root.sh install-magisk",
    "remove": "/system/bin/twrp_root.sh remove",
    # keep TWRP after an OTA (twrp_install_slot.sh)
    "twrp-install-other": "/system/bin/twrp_install_slot.sh other",
    "twrp-install-both": "/system/bin/twrp_install_slot.sh both",
    # /data encryption via bundled DFE-NEO (twrp_encryption.sh). The GUI only
    # formats /data after encryption-disable / encryption-enable succeed.
    "encryption-status": "/system/bin/twrp_encryption.sh status",
    "encryption-dryrun": "/system/bin/twrp_encryption.sh dryrun",
    "encryption-disable": "/system/bin/twrp_encryption.sh disable",
    "encryption-postformat": "/system/bin/twrp_encryption.sh postformat",
    "encryption-enable": "/system/bin/twrp_encryption.sh enable",
    # Advanced > TOOLS > Collect logs (twrp_collect_logs.sh)
    "collect-logs": "/system/bin/twrp_collect_logs.sh",
}

UPDATE_BINARY = """#!/system/bin/bash
# TWRP menu shim for: {command}
# Generated by mkrootzips.py - do not edit by hand.
OUTFD="$2"
ui_print() {{ printf 'ui_print %s\\nui_print\\n' "$1" >&"$OUTFD"; }}
set -o pipefail
ui_print "== {name} (slot $(getprop ro.boot.slot_suffix))"
{command} 2>&1 | while IFS= read -r line; do ui_print "$line"; done
rc=$?
[ "$rc" -eq 0 ] || ui_print "!! {name} failed (exit $rc)"
exit "$rc"
"""


def fixed_info(name, mode):
    info = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
    info.external_attr = (stat.S_IFREG | mode) << 16
    info.compress_type = zipfile.ZIP_DEFLATED
    return info


def main():
    os.makedirs(OUT, exist_ok=True)
    for name, command in ACTIONS.items():
        path = os.path.join(OUT, f"{name}.zip")
        with zipfile.ZipFile(path, "w") as z:
            z.writestr(fixed_info("META-INF/com/google/android/update-binary", 0o755),
                       UPDATE_BINARY.format(name=name, command=command))
            z.writestr(fixed_info("META-INF/com/google/android/updater-script", 0o644),
                       "# dummy - see update-binary\n")
        print(f"  wrote {os.path.relpath(path, HERE)}")


if __name__ == "__main__":
    main()
